### ISSUE TITLE
Fix bounties being shown for all players

### ISSUE THREAD

**Issue by tpdjairks** [FlyOutBoy/BvO-Another#92]
Make kill gold text overlay +50, +300, etc. visible only for killer. Currently whole team can see and it's confusing who got the kill.
![image](https://user-images.githubusercontent.com/110841373/186561558-d19ebd60-386d-4e8d-9178-e43a835b80af.png)
Look on minimap lol, I'm in base even. This + gold needs to be shown only to player who got the kill.

**Comment by FlyOutBoy** [comment]
done

**Comment by tpdjairks** [comment]
Uhmm,  in this version that I have which you told me to test sphere
![image](https://user-images.githubusercontent.com/110841373/186776794-13b935f6-c8da-4cb2-92a1-e1ed61febd20.png)
It's not fixed. And I didn't notice it before but, can even see the gold acquired by enemy team kills lol.

**Comment by FlyOutBoy** [comment]
done
